apiVersion: v1
kind: Pod
metadata:
  name: production-frontend
  labels:
    app: front
spec:
  containers:
    - name: production-frontend
      image: nyamtsu/react:v1
      ports:
        - containerPort: 80
